# Pandas
Welcome to the fifth lesson! This Jupyter Notebook file is meant to accompany **L05 - Pandas.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

In [1]:
import pandas as pd

### 1. Introduction to Pandas

In [2]:
manual_dataframe = pd.DataFrame({
    'Current_Price': [223.84, 1970.19, 113.37],
    'Name': ['Apple', 'Amazon', 'Microsoft'],
    'Ticker': ['AAPL', 'AMZN', 'MSFT'],
})
manual_dataframe

   Current_Price       Name Ticker
0         223.84      Apple   AAPL
1        1970.19     Amazon   AMZN
2         113.37  Microsoft   MSFT

In [3]:
excel_dataframe = pd.read_excel('data/excel_stocks.xlsx')
excel_dataframe

   Current_Price       Name Ticker
0         223.84      Apple   AAPL
1        1970.19     Amazon   AZMN
2         113.37  Microsoft   MSFT

In [4]:
excel_dataframe.head(2)

   Current_Price    Name Ticker
0         223.84   Apple   AAPL
1        1970.19  Amazon   AZMN

In [5]:
excel_dataframe.tail(2)

   Current_Price       Name Ticker
1        1970.19     Amazon   AZMN
2         113.37  Microsoft   MSFT

In [6]:
excel_dataframe.shape

(3, 3)

### 2. New Object Type: Pandas DataFrames

<font color = 'blue'> **EXERCISE 2.1** </font>

![instructions](figures/exercise_2_1_instructions.png)

In [7]:
stock_data = pd.read_csv('data/stock_data.csv')
stock_data.shape

(100, 7)

In [8]:
stock_data.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30

In [9]:
stock_data.tail(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68

<font color = 'blue'> **EXERCISE 2.2** </font>

![instructions](figures/exercise_2_2_instructions.png)

In [10]:
print(stock_data.select_dtypes(include='number').min())
print('---')
print(stock_data.select_dtypes(include='number').max())

Beta                    0.22
Market Cap       63890227.00
Current Price          12.68
Price Target           15.56
dtype: float64
---
Beta             1.840000e+00
Market Cap       1.081131e+09
Current Price    3.249990e+05
Price Target     3.571250e+05
dtype: float64

In [11]:
print(stock_data.describe())

             Beta    Market Cap  Current Price   Price Target
count  100.000000  1.000000e+02     100.000000      93.000000
mean     0.995800  1.756136e+08    3441.165500    4051.011720
std      0.283446  1.806083e+08   32481.881894   37011.566893
min      0.220000  6.389023e+07      12.680000      15.560000
25%      0.810000  8.195384e+07      69.630000      74.530000
50%      0.990000  1.119556e+08     117.600000     123.930000
75%      1.182500  1.987309e+08     219.430000     217.130000
max      1.840000  1.081131e+09  324999.000000  357125.000000

### 3. New Object Type: Pandas Series

In [12]:
# Practice
type(stock_data)
stock_data.Beta

0     1.09
1     1.23
2     1.46
3     1.44
4     1.13
      ...
95    0.46
96    1.32
97    0.96
98    0.74
99    1.01
Name: Beta, Length: 100, dtype: float64

In [13]:
stock_data.columns = stock_data.columns.str.strip().str.replace(" ", "_").str.lower()

In [14]:
print(stock_data.columns)
stock_data.current_price

Index(['ticker', 'name', 'sector', 'beta', 'market_cap', 'current_price',
       'price_target'],
      dtype='object')

0        223.84
1       1970.19
2        113.37
3       1177.98
4     324999.00
        ...
95       147.19
96       568.36
97       147.46
98        43.80
99       188.22
Name: current_price, Length: 100, dtype: float64

<font color = 'blue'> **EXERCISE 3.1** </font>

![Instructions](figures/exercise_3_1_instructions.png)

In [15]:
stock_data.columns

Index(['ticker', 'name', 'sector', 'beta', 'market_cap', 'current_price',
       'price_target'],
      dtype='object')

In [16]:
stock_data.head(1)

,ticker,name,sector,beta,market_cap,current_price,price_target
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27

In [17]:
stock_data['price_increase'] = round(stock_data.price_target - stock_data.current_price, 3)
print(stock_data.columns)
stock_data

Index(['ticker', 'name', 'sector', 'beta', 'market_cap', 'current_price',
       'price_target', 'price_increase'],
      dtype='object')

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,206.91
4,BRK/A,BERKSHIRE HATH-A,Financials,1.13,534247506,324999.00,357125.00,32126.00
...,...,...,...,...,...,...,...,...
95,AMT,AMERICAN TOWER C,Real Estate,0.46,64886514,147.19,160.68,13.49
96,ISRG,INTUITIVE SURGIC,Health Care,1.32,64649581,568.36,556.59,-11.77
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,-1.73
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20,5.40
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68,23.46

In [18]:
stock_data.head(1)

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43

In [19]:
stock_data['return'] = round(stock_data.price_increase / stock_data.current_price, 3)
stock_data

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase,return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.038
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.083
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.079
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,206.91,0.176
4,BRK/A,BERKSHIRE HATH-A,Financials,1.13,534247506,324999.00,357125.00,32126.00,0.099
...,...,...,...,...,...,...,...,...,...
95,AMT,AMERICAN TOWER C,Real Estate,0.46,64886514,147.19,160.68,13.49,0.092
96,ISRG,INTUITIVE SURGIC,Health Care,1.32,64649581,568.36,556.59,-11.77,-0.021
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,-1.73,-0.012
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20,5.40,0.123
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68,23.46,0.125

In [20]:
print(stock_data.head(1))
stock_data['return'].describe()

  ticker       name                  sector  beta  market_cap  current_price  \
0   AAPL  APPLE INC  Information Technology  1.09  1081130615         223.84

   price_target  price_increase  return
0        232.27            8.43   0.038

count    93.000000
mean      0.093785
std       0.073745
min      -0.047000
25%       0.035000
50%       0.079000
75%       0.149000
max       0.270000
Name: return, dtype: float64

### 4. Filtering Data with Boolean Masks

<font color = 'blue'> **EXERCISE 4.1** </font>

![Instructions](figures/exercise_4_1_instructions.png)

In [21]:
stock_data.head(3)

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase,return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.038
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.083
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.079

In [22]:
# create a boolean mask
boolean_mask = stock_data['sector'] == 'Information Technology'
stock_data[boolean_mask]

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase,return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.038
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.079
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,206.91,0.176
5,FB,FACEBOOK INC-A,Information Technology,1.33,468653343,162.32,205.93,43.61,0.269
10,V,VISA INC-CLASS A,Information Technology,1.15,300743721,147.84,159.43,11.59,0.078
18,MA,MASTERCARD INC-A,Information Technology,1.18,226341093,217.96,228.18,10.22,0.047
21,CSCO,CISCO SYSTEMS,Information Technology,1.30,216681234,47.40,50.15,2.75,0.058
22,INTC,INTEL CORP,Information Technology,1.58,209984946,45.54,56.18,10.64,0.234
25,ORCL,ORACLE CORP,Information Technology,1.02,196071883,49.25,54.48,5.23,0.106
37,IBM,IBM,Information Technology,0.98,135390904,148.33,165.10,16.77,0.113
38,ADBE,ADOBE SYS INC,Information Technology,1.34,134505431,274.69,288.31,13.62,0.050
46,CRM,SALESFORCE.COM,Information Technology,1.12,119172686,157.49,169.68,12.19,0.077
50,QCOM,QUALCOMM INC,Information Technology,1.28,110315545,75.09,71.57,-3.52,-0.047
53,PYPL,PAYPAL HOLDINGS,Information Technology,1.25,107453792,90.78,97.83,7.05,0.078
58,TXN,TEXAS INSTRUMENT,Information Technology,1.36,102430474,105.36,123.93,18.57,0.176
60,AVGO,BROADCOM INC,Information Technology,0.99,97714004,236.34,286.03,49.69,0.210
92,VMW,VMWARE INC-CL A,Information Technology,1.21,66480574,162.65,165.20,2.55,0.016
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,-1.73,-0.012

In [23]:
# Indicator Variable for IT
stock_data['is_tech'] = (stock_data['sector'] == 'Information Technology').astype(int)
stock_data

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase,return,is_tech
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.038,1
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.083,0
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.079,1
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,206.91,0.176,1
4,BRK/A,BERKSHIRE HATH-A,Financials,1.13,534247506,324999.00,357125.00,32126.00,0.099,0
...,...,...,...,...,...,...,...,...,...,...
95,AMT,AMERICAN TOWER C,Real Estate,0.46,64886514,147.19,160.68,13.49,0.092,0
96,ISRG,INTUITIVE SURGIC,Health Care,1.32,64649581,568.36,556.59,-11.77,-0.021,0
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,-1.73,-0.012,1
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20,5.40,0.123,0
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68,23.46,0.125,0

In [24]:
stock_data.head(3)

,ticker,name,sector,beta,market_cap,current_price,price_target,price_increase,return,is_tech
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.038,1
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.083,0
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.079,1

### 5. Segmenting Data with Groupby

<font color = 'blue'> **EXERCISE 5.1** </font>

![Instructions](figures/exercise_5_1_instructions.png)

In [26]:
stock_data.groupby('sector')[stock_data.select_dtypes(include='number').columns].mean()

,beta,market_cap,current_price,price_target,price_increase,return,is_tech
sector,,,,,,,
Consumer Discretionary,0.907692,1.875567e+08,422.383846,468.329231,45.945385,0.086692,0.0
Consumer Staples,0.675000,1.392211e+08,88.859000,94.648000,5.789000,0.079100,0.0
Energy,0.910000,1.865371e+08,83.757500,97.650000,13.892500,0.164500,0.0
Enersy,0.860000,6.824144e+07,117.820000,140.690000,22.870000,0.194000,0.0
Financials,1.155000,1.856177e+08,27198.074167,29894.575833,2696.501667,0.137000,0.0
Health Care,0.954211,1.275709e+08,177.760000,186.905789,9.145789,0.056842,0.0
Industrial$,1.190000,1.219452e+08,207.880000,217.130000,9.250000,0.044000,0.0
Industrials,1.032500,1.189380e+08,179.236250,198.453750,19.217500,0.112875,0.0
Information Technology,1.224444,2.958042e+08,199.093889,222.621667,23.527778,0.097000,1.0
Information Technology .,1.840000,1.680694e+08,276.430000,286.090000,9.660000,0.035000,0.0
Materials,1.360000,1.582399e+08,68.580000,81.260000,12.680000,0.185000,0.0
Real Estate,0.460000,6.488651e+07,147.190000,160.680000,13.490000,0.092000,0.0
Telecommunication Services,0.665000,2.347001e+08,44.075000,46.020000,1.945000,0.048000,0.0
Utilities,0.220000,8.189415e+07,173.650000,176.720000,3.070000,0.018000,0.0
lndustrials,1.120000,6.754730e+07,255.440000,283.180000,27.740000,0.109000,0.0